### ISSUE TITLE
Consider moving to JuliaPlots

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaPlots/InspectDR.jl#34]
I am currently in the process of preventing that Plots.jl's backends go unmaintained so I'd like you to think about moving this repository even if you currently think this may never happen in your case, since usually people are pretty bad at predicting when that happens ;)

Best,
Simon

**Comment by ma-laforge** [comment]
Hi Simon!
Sorry: I didn't even see this (I haven't been active here in quit a while)

Agreed: This is a problem. Maintaining something that I don't currently need is not all that practical.
- particularly when I have other priorities.

I don't mind transferring over InspectDR to Julia plots - especially if people want to enhance it.

I'm not sure this is still something you want to do anymore - given that you've recently removed InspectDR from Plots.jl.

Let me know.

**Comment by ma-laforge** [comment]
Ok. I tried transferring, but I got:
"You don’t have the permission to create public repositories on JuliaPlots."

Thought I was making a request to be approved by the organization - but I guess not.

Please let me know how to proceed.

**Comment by BeastyBlacksmith** [comment]
I sent you an invite, you should be able to do that after accepting it.

**Comment by BeastyBlacksmith** [comment]
> I'm wondering if Plots.jl also wanted NumericIO.jl

sure

**Comment by ma-laforge** [comment]
Ok. Transfered NumericIO as well.
